/* ZALI Industries - Product Catalog Data */
/* Auto-generated by generate-products-data.ps1 */
/* DO NOT EDIT MANUALLY */

window.ZALI_CATALOG = {
  categories: [
  ]
};

/* --- Flat lookup by product id --- */
window.ZALI_PRODUCT_MAP = {};
window.ZALI_CATALOG.categories.forEach(cat => {
  cat.subcategories.forEach(sub => {
    sub.products.forEach(p => {
      window.ZALI_PRODUCT_MAP[p.id] = p;
    });
  });
});
