const express = require('express');
const sqlite3 = require('sqlite3').verbose();
const session = require('express-session');
const bcrypt = require('bcrypt');
const multer = require('multer');
const path = require('path');
const fs = require('fs');

const app = express();
const db = new sqlite3.Database(path.join(__dirname, 'database.sqlite'));

// Ensure uploads directory exists
const uploadDir = path.join(__dirname, 'public', 'images', 'uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

// Multer setup
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, uploadDir)
  },
  filename: function (req, file, cb) {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9)
    cb(null, uniqueSuffix + path.extname(file.originalname))
  }
});
const upload = multer({ storage: storage });

// Middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(session({
  secret: 'zali-secret-key-12345',
  resave: false,
  saveUninitialized: false,
  cookie: { maxAge: 24 * 60 * 60 * 1000 } // 1 day
}));

// Static files (Front-end)
app.use(express.static(path.join(__dirname, 'public')));

// Auth Middleware
function isAuthenticated(req, res, next) {
  if (req.session.adminId) {
    return next();
  }
  if (req.path.startsWith('/api/')) {
    return res.status(401).json({ error: 'Unauthorized. Please refresh and log in again.' });
  }
  res.redirect('/login');
}

// ========================
// STATIC SITE GENERATOR
// ========================
async function regenerateCatalog() {
  return new Promise((resolve, reject) => {
    console.log('Regenerating products-data.js...');
    
    db.all('SELECT * FROM categories ORDER BY sort_order ASC, id ASC', [], (err, categories) => {
      if (err) return reject(err);
      
      db.all('SELECT * FROM subcategories ORDER BY sort_order ASC, id ASC', [], (err, subcategories) => {
        if (err) return reject(err);
        
        db.all('SELECT * FROM products', [], (err, products) => {
          if (err) return reject(err);
          
          db.all('SELECT * FROM fabrics', [], (err, fabrics) => {
            if (err) return reject(err);

            const catalog = { categories: [] };
            
            categories.forEach(cat => {
              const catObj = {
                id: cat.id,
                name: cat.name,
                slug: cat.slug,
                subcategories: []
              };
              
              const catSubs = subcategories.filter(s => s.categoryId === cat.id);
              catSubs.forEach(sub => {
                const subObj = {
                  id: sub.id,
                  name: sub.name,
                  slug: sub.slug,
                  products: []
                };
                if (sub.group_name) {
                  subObj.group = sub.group_name;
                }
                
                const subProds = products.filter(p => p.subcategoryId === sub.id);
                subProds.forEach(prod => {
                  subObj.products.push({
                    id: prod.id,
                    name: prod.name,
                    folderName: prod.folderName,
                    category: cat.name,
                    categoryId: cat.id,
                    subcategory: sub.name,
                    subcategoryId: sub.id,
                    gender: prod.gender,
                    title: prod.title,
                    description: prod.description,
                    garmentType: prod.garmentType,
                    fabric: prod.fabric,
                    printMethods: prod.printMethods,
                    sizeRange: prod.sizeRange,
                    leadTime: prod.leadTime,
                    moq: prod.moq,
                    is_featured: prod.is_featured === 1,
                    primaryImageKey: prod.primary_image_key || null,
                    images: JSON.parse(prod.images || '{}')
                  });
                });
                catObj.subcategories.push(subObj);
              });
              catalog.categories.push(catObj);
            });
            
            const output = `/* ZALI Industries - Product Catalog Data */\n/* Auto-generated by Node.js Backend */\n\nwindow.ZALI_CATALOG = ${JSON.stringify(catalog, null, 2)};\n\n/* --- Flat lookup by product id --- */\nwindow.ZALI_PRODUCT_MAP = {};\nwindow.ZALI_CATALOG.categories.forEach(cat => {\n  cat.subcategories.forEach(sub => {\n    sub.products.forEach(p => {\n      window.ZALI_PRODUCT_MAP[p.id] = p;\n    });\n  });\n});\n`;
            fs.writeFileSync(path.join(__dirname, 'public', 'products-data.js'), output, 'utf8');

            const parsedFabrics = (fabrics || []).map(f => {
              let parsedImage = f.image;
              if (f.image && typeof f.image === 'string' && f.image.startsWith('[')) {
                try { parsedImage = JSON.parse(f.image); } catch (e) {}
              }
              return { ...f, image: parsedImage };
            });
            const fabricsOutput = `window.ZALI_FABRICS = ${JSON.stringify(parsedFabrics, null, 2)};\n`;
            fs.writeFileSync(path.join(__dirname, 'public', 'fabrics-data.js'), fabricsOutput, 'utf8');

            console.log('Successfully regenerated products-data.js and fabrics-data.js!');
            resolve();
          });
        });
      });
    });
  });
}

// ========================
// ROUTES
// ========================

// Admin Login UI
app.get('/login', (req, res) => {
  res.send(`
    <html><head><title>ZALI Admin Login</title>
    <style>
      body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; background: #f4f4f4; }
      .box { background: white; padding: 40px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); width: 300px; }
      input { width: 100%; padding: 10px; margin: 10px 0; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }
      button { width: 100%; padding: 10px; background: #e34c26; color: white; border: none; border-radius: 4px; cursor: pointer; }
    </style></head>
    <body>
      <div class="box">
        <h2>Admin Login</h2>
        <form method="POST" action="/login">
          <input type="text" name="username" placeholder="Username" required>
          <input type="password" name="password" placeholder="Password" required>
          <button type="submit">Login</button>
        </form>
      </div>
    </body></html>
  `);
});

// Admin Login POST
app.post('/login', (req, res) => {
  const { username, password } = req.body;
  db.get('SELECT * FROM admins WHERE username = ?', [username], async (err, row) => {
    if (row && await bcrypt.compare(password, row.passwordHash)) {
      req.session.adminId = row.id;
      res.redirect('/admin');
    } else {
      res.send('Invalid credentials. <a href="/login">Try again</a>');
    }
  });
});

app.get('/logout', (req, res) => {
  req.session.destroy();
  res.redirect('/');
});

// Admin Dashboard UI
app.get('/admin', isAuthenticated, (req, res) => {
  res.sendFile(path.join(__dirname, 'admin.html'));
});

// ========================
// API (Secure CRUD)
// ========================

app.get('/api/catalog', isAuthenticated, (req, res) => {
  // Returns raw tables for the admin dashboard
  db.all('SELECT * FROM categories ORDER BY sort_order ASC, id ASC', [], (err, categories) => {
    db.all('SELECT * FROM subcategories ORDER BY sort_order ASC, id ASC', [], (err, subcategories) => {
      db.all('SELECT * FROM products', [], (err, products) => {
        db.all('SELECT * FROM fabrics', [], (err, fabrics) => {
          const parsedProducts = (products || []).map(p => {
            let parsedImages = p.images;
            if (p.images && typeof p.images === 'string' && p.images.startsWith('{')) {
              try { parsedImages = JSON.parse(p.images); } catch (e) {}
            }
            return { ...p, images: parsedImages };
          });
          const parsedFabrics = (fabrics || []).map(f => {
            let parsedImage = f.image;
            if (f.image && typeof f.image === 'string' && f.image.startsWith('[')) {
              try { parsedImage = JSON.parse(f.image); } catch (e) {}
            }
            return { ...f, image: parsedImage };
          });
          db.all('SELECT * FROM fabric_families', [], (err, fabric_families) => {
            res.json({ categories, subcategories, products: parsedProducts, fabrics: parsedFabrics, fabric_families });
          });
        });
      });
    });
  });
});

app.post('/api/upload', isAuthenticated, upload.single('image'), (req, res) => {
  if (!req.file) return res.status(400).send('No file uploaded.');
  // Return the relative path to be saved in DB
  const relPath = 'images/uploads/' + req.file.filename;
  res.json({ path: relPath });
});

// Fabric Families API
app.post('/api/fabric_families', isAuthenticated, (req, res) => {
  const { id, name, description } = req.body;
  db.run(`INSERT INTO fabric_families (id, name, description) VALUES (?, ?, ?)`, [id, name, description], function(err) {
    if (err) return res.status(500).send(err.message);
    res.json({ success: true, id });
  });
});

app.put('/api/fabric_families/:id', isAuthenticated, (req, res) => {
  const { name, description } = req.body;
  db.run(`UPDATE fabric_families SET name = ?, description = ? WHERE id = ?`, [name, description, req.params.id], function(err) {
    if (err) return res.status(500).send(err.message);
    res.json({ success: true });
  });
});

app.delete('/api/fabric_families/:id', isAuthenticated, (req, res) => {
  db.run(`DELETE FROM fabric_families WHERE id = ?`, [req.params.id], function(err) {
    if (err) return res.status(500).send(err.message);
    res.json({ success: true });
  });
});

// Categories API
app.post('/api/categories', isAuthenticated, (req, res) => {
  const { id, name, slug } = req.body;
  db.run(`INSERT INTO categories (id, name, slug) VALUES (?, ?, ?)`, [id, name, slug], function(err) {
    if (err) return res.status(500).send(err.message);
    regenerateCatalog().then(() => res.json({ success: true, id }));
  });
});

app.delete('/api/categories/:id', isAuthenticated, (req, res) => {
  db.run(`DELETE FROM categories WHERE id = ?`, [req.params.id], function(err) {
    if (err) return res.status(500).send(err.message);
    regenerateCatalog().then(() => res.json({ success: true }));
  });
});

app.put('/api/categories/reorder', isAuthenticated, (req, res) => {
  const { order } = req.body; // Array of IDs
  if (!order || !Array.isArray(order)) return res.status(400).send('Invalid order array');
  
  let completed = 0;
  let hasError = false;
  order.forEach((id, index) => {
    db.run(`UPDATE categories SET sort_order = ? WHERE id = ?`, [index, id], (err) => {
      if (err) hasError = true;
      completed++;
      if (completed === order.length) {
        if (hasError) return res.status(500).send('Error updating some items');
        regenerateCatalog().then(() => res.json({ success: true }));
      }
    });
  });
});

// Subcategories API
app.post('/api/subcategories', isAuthenticated, (req, res) => {
  const { id, categoryId, name, slug, group_name } = req.body;
  db.run(`INSERT INTO subcategories (id, categoryId, name, slug, group_name) VALUES (?, ?, ?, ?, ?)`, 
    [id, categoryId, name, slug, group_name || null], 
    function(err) {
      if (err) return res.status(500).send(err.message);
      regenerateCatalog().then(() => res.json({ success: true, id }));
  });
});

app.delete('/api/subcategories/:id', isAuthenticated, (req, res) => {
  db.run(`DELETE FROM subcategories WHERE id = ?`, [req.params.id], function(err) {
    if (err) return res.status(500).send(err.message);
    regenerateCatalog().then(() => res.json({ success: true }));
  });
});

app.put('/api/subcategories/reorder', isAuthenticated, (req, res) => {
  const { order } = req.body; // Array of IDs
  if (!order || !Array.isArray(order)) return res.status(400).send('Invalid order array');
  
  let completed = 0;
  let hasError = false;
  order.forEach((id, index) => {
    db.run(`UPDATE subcategories SET sort_order = ? WHERE id = ?`, [index, id], (err) => {
      if (err) hasError = true;
      completed++;
      if (completed === order.length) {
        if (hasError) return res.status(500).send('Error updating some items');
        regenerateCatalog().then(() => res.json({ success: true }));
      }
    });
  });
});

app.post('/api/products', isAuthenticated, (req, res) => {
  const { id, categoryId, subcategoryId, name, gender, title, description, garmentType, fabric, printMethods, sizeRange, leadTime, moq, images, is_featured, primaryImageKey } = req.body;
  db.run(`INSERT INTO products (id, categoryId, subcategoryId, name, gender, title, description, garmentType, fabric, printMethods, sizeRange, leadTime, moq, images, is_featured, primary_image_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [id, categoryId, subcategoryId, name, gender, title, description, garmentType, fabric, printMethods, sizeRange, leadTime, moq, JSON.stringify(images), is_featured ? 1 : 0, primaryImageKey || null],
    function(err) {
      if (err) return res.status(500).send(err.message);
      regenerateCatalog().then(() => res.json({ success: true, id }));
    }
  );
});

app.put('/api/products/:id', isAuthenticated, (req, res) => {
  const { categoryId, subcategoryId, name, gender, title, description, garmentType, fabric, printMethods, sizeRange, leadTime, moq, images, is_featured, primaryImageKey } = req.body;
  db.run(`UPDATE products SET categoryId = ?, subcategoryId = ?, name = ?, gender = ?, title = ?, description = ?, garmentType = ?, fabric = ?, printMethods = ?, sizeRange = ?, leadTime = ?, moq = ?, images = ?, is_featured = ?, primary_image_key = ? WHERE id = ?`,
    [categoryId, subcategoryId, name, gender, title, description, garmentType, fabric, printMethods, sizeRange, leadTime, moq, JSON.stringify(images), is_featured ? 1 : 0, primaryImageKey || null, req.params.id],
    function(err) {
      if (err) return res.status(500).send(err.message);
      regenerateCatalog().then(() => res.json({ success: true, id: req.params.id }));
    }
  );
});

app.put('/api/products/:id/feature', isAuthenticated, (req, res) => {
  const { is_featured } = req.body;
  db.run(`UPDATE products SET is_featured = ? WHERE id = ?`, [is_featured ? 1 : 0, req.params.id], function(err) {
    if (err) return res.status(500).send(err.message);
    regenerateCatalog().then(() => res.json({ success: true }));
  });
});

app.delete('/api/products/:id', isAuthenticated, (req, res) => {
  db.run(`DELETE FROM products WHERE id = ?`, [req.params.id], function(err) {
    if (err) return res.status(500).send(err.message);
    regenerateCatalog().then(() => res.json({ success: true }));
  });
});

// Fabrics API
app.post('/api/fabrics', isAuthenticated, (req, res) => {
  const { id, family, familyDesc, name, spec, description, bestFor, metaLabel, metaValue, swatchClass, tag, image } = req.body;
  const imageStr = typeof image === 'object' ? JSON.stringify(image) : (image || null);
  db.run(`INSERT INTO fabrics (id, family, familyDesc, name, spec, description, bestFor, metaLabel, metaValue, swatchClass, tag, image) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [id, family, familyDesc, name, spec, description, bestFor, metaLabel, metaValue, swatchClass, tag, imageStr],
    function(err) {
      if (err) return res.status(500).json({ error: err.message });
      regenerateCatalog().then(() => res.json({ success: true }));
    });
});

app.put('/api/fabrics/:id', isAuthenticated, (req, res) => {
  const { family, familyDesc, name, spec, description, bestFor, metaLabel, metaValue, swatchClass, tag, image } = req.body;
  const imageStr = typeof image === 'object' ? JSON.stringify(image) : (image || null);
  db.run(`UPDATE fabrics SET family = ?, familyDesc = ?, name = ?, spec = ?, description = ?, bestFor = ?, metaLabel = ?, metaValue = ?, swatchClass = ?, tag = ?, image = ? WHERE id = ?`,
    [family, familyDesc, name, spec, description, bestFor, metaLabel, metaValue, swatchClass, tag, imageStr, req.params.id],
    function(err) {
      if (err) return res.status(500).json({ error: err.message });
      regenerateCatalog().then(() => res.json({ success: true }));
    });
});

app.delete('/api/fabrics/:id', isAuthenticated, (req, res) => {
  db.run(`DELETE FROM fabrics WHERE id = ?`, [req.params.id], function(err) {
    if (err) return res.status(500).send(err.message);
    regenerateCatalog().then(() => res.json({ success: true }));
  });
});

// Start Server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
