const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const sqlite3 = require('sqlite3').verbose();

const TARGET_DIR = path.join(__dirname, '../public/FinalAllProductsZali/Downloads');
const DB_PATH = path.join(__dirname, '../database.sqlite');
const MAX_WIDTH = 1000;
const QUALITY = 80;

// Recursive function to get all image files
function getFiles(dir, files = []) {
  const list = fs.readdirSync(dir);
  for (const file of list) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      getFiles(filePath, files);
    } else {
      const ext = path.extname(file).toLowerCase();
      if (['.jpg', '.jpeg', '.png'].includes(ext)) {
        files.push(filePath);
      }
    }
  }
  return files;
}

async function convertImages() {
  console.log('Scanning for images in', TARGET_DIR);
  if (!fs.existsSync(TARGET_DIR)) {
    console.log('Directory not found. Skipping image conversion.');
    return;
  }

  const files = getFiles(TARGET_DIR);
  console.log(`Found ${files.length} images to convert.`);

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const ext = path.extname(file);
    const newFile = file.slice(0, -ext.length) + '.webp';

    console.log(`[${i + 1}/${files.length}] Converting: ${path.basename(file)} -> ${path.basename(newFile)}`);

    try {
      await sharp(file)
        .resize({ width: MAX_WIDTH, withoutEnlargement: true })
        .webp({ quality: QUALITY })
        .toFile(newFile);

      // Delete original
      fs.unlinkSync(file);
    } catch (err) {
      console.error(`Error processing ${file}:`, err);
    }
  }

  console.log('Finished converting images.');
}

async function updateDatabase() {
  console.log('Updating database...');
  return new Promise((resolve, reject) => {
    const db = new sqlite3.Database(DB_PATH, (err) => {
      if (err) return reject(err);
    });

    db.all('SELECT id, images FROM products', (err, rows) => {
      if (err) {
        db.close();
        return reject(err);
      }

      const stmt = db.prepare('UPDATE products SET images = ? WHERE id = ?');
      let count = 0;

      for (const row of rows) {
        if (!row.images) continue;

        let modified = false;
        let imagesJson = row.images;

        // Replace .png, .jpg, .jpeg with .webp in the string
        const newImagesJson = imagesJson.replace(/\.(png|jpg|jpeg)/gi, '.webp');

        if (imagesJson !== newImagesJson) {
          stmt.run(newImagesJson, row.id);
          count++;
        }
      }

      stmt.finalize();
      db.close((err) => {
        if (err) return reject(err);
        console.log(`Updated ${count} records in database.`);
        resolve();
      });
    });
  });
}

// In server.js we have generateProductsData... but we can just write it here to be safe
function generateProductsDataScript() {
  console.log('Regenerating products-data.js...');
  const db = new sqlite3.Database(DB_PATH);
  
  db.all('SELECT * FROM products', (err, rows) => {
    if (err) {
      console.error(err);
      return;
    }
    
    // Group into categories
    const catalog = { categories: [] };
    const catMap = {};

    rows.forEach(p => {
      if (!catMap[p.categoryId]) {
        catMap[p.categoryId] = {
          id: p.categoryId,
          name: p.category,
          slug: p.categoryId,
          subcategories: []
        };
        catalog.categories.push(catMap[p.categoryId]);
      }

      const cat = catMap[p.categoryId];
      let sub = cat.subcategories.find(s => s.id === p.subcategoryId);
      if (!sub) {
        sub = {
          id: p.subcategoryId,
          name: p.subcategory,
          slug: p.subcategoryId.split('-').pop(), // approximate slug
          products: []
        };
        cat.subcategories.push(sub);
      }

      let parsedImages = {};
      try { parsedImages = JSON.parse(p.images); } catch(e){}

      sub.products.push({
        id: p.id,
        name: p.name,
        folderName: p.folderName,
        category: p.category,
        categoryId: p.categoryId,
        subcategory: p.subcategory,
        subcategoryId: p.subcategoryId,
        gender: p.gender,
        title: p.title,
        description: p.description,
        garmentType: p.garmentType,
        fabric: p.fabric,
        moq: p.moq,
        images: parsedImages
      });
    });

    const output = `/* ZALI Industries - Product Catalog Data */
/* Auto-generated by server.js / convert-images.js */
/* DO NOT EDIT MANUALLY */

window.ZALI_CATALOG = ${JSON.stringify(catalog, null, 2)};
`;

    const outputPath = path.join(__dirname, '../public/products-data.js');
    fs.writeFileSync(outputPath, output, 'utf8');
    console.log('Successfully regenerated products-data.js!');
  });
}

async function run() {
  try {
    await convertImages();
    await updateDatabase();
    generateProductsDataScript();
  } catch (e) {
    console.error('Failed:', e);
  }
}

run();
