const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const fs = require('fs');

const db = new sqlite3.Database(path.join(__dirname, '../database.sqlite'));

db.all('SELECT * FROM categories', [], (err, categories) => {
  if (err) throw err;
  db.all('SELECT * FROM subcategories', [], (err, subcategories) => {
    if (err) throw err;
    db.all('SELECT * FROM products', [], (err, products) => {
      if (err) throw err;
      const catalog = { categories: [] };
      
      categories.forEach(cat => {
        const catObj = {
          id: cat.id,
          name: cat.name,
          slug: cat.slug,
          subcategories: []
        };
        
        const catSubs = subcategories.filter(s => s.categoryId === cat.id);
        catSubs.forEach(sub => {
          const subObj = {
            id: sub.id,
            name: sub.name,
            slug: sub.slug,
            products: []
          };
          if (sub.group_name) {
            subObj.group = sub.group_name;
          }
          
          const subProds = products.filter(p => p.subcategoryId === sub.id);
          subProds.forEach(prod => {
            subObj.products.push({
              id: prod.id,
              name: prod.name,
              folderName: prod.folderName,
              category: cat.name,
              categoryId: cat.id,
              subcategory: sub.name,
              subcategoryId: sub.id,
              gender: prod.gender,
              title: prod.title,
              description: prod.description,
              garmentType: prod.garmentType,
              fabric: prod.fabric,
              moq: prod.moq,
              images: JSON.parse(prod.images || '{}')
            });
          });
          catObj.subcategories.push(subObj);
        });
        catalog.categories.push(catObj);
      });
      
      const output = `/* ZALI Industries - Product Catalog Data */\n/* Auto-generated by Node.js Backend */\n\nwindow.ZALI_CATALOG = ${JSON.stringify(catalog, null, 2)};\n\n/* --- Flat lookup by product id --- */\nwindow.ZALI_PRODUCT_MAP = {};\nwindow.ZALI_CATALOG.categories.forEach(cat => {\n  cat.subcategories.forEach(sub => {\n    sub.products.forEach(p => {\n      window.ZALI_PRODUCT_MAP[p.id] = p;\n    });\n  });\n});\n`;
      fs.writeFileSync(path.join(__dirname, '../public', 'products-data.js'), output, 'utf8');
      console.log('Successfully regenerated products-data.js using proper categories/subcategories!');
    });
  });
});
